version: "3"

services:

  application-server:
    image: "codelabs-application-server"
    build: 
      context: "./application-server/"
    ports:
      - "5000:5000"
    volumes:
      - ${PWD}/application-server/public:/app/public
      - ${PWD}/application-server/index.js:/app/index.js
      - ${PWD}/application-server/package.json:/app/package.json
    depends_on:
      - react-dev-server
      - code-execution-api
      - matchmaking-service
    network_mode: "bridge"
    environment:
      IP_ADDRESS: ${IP_ADDRESS:-localhost}

  react-dev-server:
    image: "codelabs-react-dev-server"
    build:
      context: "./react-dev-server/"
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/react-dev-server/src:/app/src
      - ${PWD}/react-dev-server/package.json:/app/package.json
      - ${PWD}/react-dev-server/public:/app/public
    network_mode: "bridge"
    environment:
      REACT_APP_HOST_IP_ADDRESS: ${IP_ADDRESS:-localhost}

  lab-server:
    image: "codelabs-lab-server"
    build:
      context: "./lab-server/"
    ports:
      - "0:7000"
    volumes:
      - ${PWD}/lab-server/utils:/app/utils
      - ${PWD}/lab-server/index.js:/app/index.js
      - ${PWD}/lab-server/package.json:/app/package.json
    network_mode: "bridge"

  code-execution-api:
    image: "codelabs-code-execution-api"
    build:
      context: "./code-execution-api/"
    ports:
      - "4000:4000"
    volumes:
      - ${PWD}/code-execution-api/index.js:/app/index.js
      - ${PWD}/code-execution-api/package.json:/app/package.json
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "bridge"

  matchmaking-service:
    image: "codelabs-matchmaking-service"
    build:
      context: "./matchmaking-service/"
    ports:
      - "10000:10000"
    volumes:
      - ${PWD}/matchmaking-service/index.js:/app/index.js
      - ${PWD}/matchmaking-service/package.json:/app/package.json
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "bridge"

  # environment:
  #   - NODE_OPTIONS=--max-old-space-size=4096
  